#!/bin/sh

# commented and this was moved to isf-panel-efl code
#while [ ! -f /tmp/.wm_ready ];
#do
#	sleep 0.1
#done

while [ ! -f /tmp/amd_ready ];
do
        /bin/sleep 0.1
done

vconf_set_safemode()
{
	if [ -f /opt/etc/.safeboot ]
	then
		/usr/bin/vconftool set -t int memory/idle-screen/safemode "1" -f
	else
		/usr/bin/vconftool set -t int memory/idle-screen/safemode "0" -f
	fi
}
vconf_set_safemode

echo -e "<2>[${_G}menu-daemon start${C_}]" > /dev/kmsg
/usr/bin/starter &

