#!/bin/sh
vconf_set_safemode()
{
	if [ -f /opt/etc/.safemode ]
	then
		vconftool set -t int memory/idle-screen/safemode "1" -i -f
	else
		vconftool set -t int memory/idle-screen/safemode "0" -i -f
	fi
}
vconf_set_safemode

echo -e "<2>[${_G}menu-daemon start${C_}]" > /dev/kmsg
/usr/bin/starter &
