#!/bin/sh
vconf_set_safemode()
{
	if [ -f /opt/etc/.safeboot ]
	then
		vconftool set -t int memory/idle-screen/safemode "1" -i -f -s system::vconf_inhouse
	else
		vconftool set -t int memory/idle-screen/safemode "0" -i -f -s system::vconf_inhouse
	fi
}
vconf_set_safemode

echo -e "<2>[${_G}menu-daemon start${C_}]" > /dev/kmsg
/usr/bin/starter &
