#!/bin/sh

CURRENT_RUNLEVEL=`basename $PWD`
# CURRENT_RUNLEVEL could be "rc3.d" or "rc4.d"

if [ x"$CURRENT_RUNLEVEL" == x"rc3.d" ]; then
	while [ ! -f /tmp/.wm_ready ];
	do
		/bin/sleep 0.1
	done
fi

/usr/bin/starter &


