#!/bin/sh

vconftool set -t int "memory/starter/sequence" 0 -i -u 5000 -g 5000

vconftool set -t string file/private/lockscreen/pkgname "org.tizen.lockscreen" -u 5000 -g 5000

vconftool -i set -t int memory/idle_lock/state "0" -u 5000 -g 5000

vconftool -i set -t bool memory/lockscreen/phone_lock_verification "0" -u 5000 -g 5000

ln -sf /etc/init.d/rd4starter /etc/rc.d/rc4.d/S81starter
ln -sf /etc/init.d/rd3starter /etc/rc.d/rc3.d/S43starter

sync
